name: Simple Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create build directory
      run: mkdir -p build/libs
        
    - name: Create simple JAR
      run: |
        # Create a basic JAR with all our files
        jar cvf build/libs/smolpeople-mod.jar -C src/main/java . -C src/main/resources .
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SmolPeople-Mod
        path: build/libs/*.jar
