name: Simple Build 1.21.4

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Create build directory
      run: mkdir -p build/libs
        
    - name: Create simple JAR for 1.21.4
      run: |
        # Create a basic JAR with all our updated files
        jar cvf build/libs/smolpeople-1.21.4.jar -C src/main/java . -C src/main/resources .
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SmolPeople-Mod-1.21.4
        path: build/libs/*.jar
